// with-vuex/src/components/TodoFooter.vue
<template>
    <!--template必须有一个根节点-->
    <div>
      <div class="col-xs-4 ">
        <button class="btn btn-primary" disabled v-show="haveUnfinished">待办事项数量<a href="#" class="badge">{{unFinishedCount}}</a></button>
      </div>
      <div class="col-xs-5">
        <button class="btn btn-sm btn-default" :style="{marginLeft: '5px'}" v-for="btn in btns" @click="tell(btn.type)" :class="{success: btn.type === filtertype}" :type="btn.type">
          {{btn.text}}
        </button>
      </div>
      <div class="col-xs-3">
        <button class="btn btn-danger btn-sm" @click="clear" v-show="haveFinished">删除已完成</button>
      </div>
    </div>
</template>
<script>
  import * as filterTypes from './filter-types'
  import * as types from '../store/types'
  import {mapActions, mapState, mapGetters} from 'vuex';
    export default {
        data() {
            return {
                btns :[
                    {type: filterTypes.ALL, text: "所有"},
                    {type: filterTypes.ACTIVE, text: "未完成"},
                    {type: filterTypes.COMPLETED, text: "已完成"}
                ],
            }

        },
        updated() {
          console.log(this.filtertype);
        },
        props: ["filtertype"],
        components: {},
        methods: {
          ...mapActions([types.CLEAR_COMPLETED, types.CHANGE_FILTER]),
          clear() {
            this[types.CLEAR_COMPLETED]();
          },
          tell(type) {
            this.$emit("changefilter", type);
          }
        },
        computed: {
          ...mapState(['todos']),
          ...mapGetters(['haveUnfinished', 'haveFinished']),
          unFinishedCount() {
//              return this.todos.reduce((count, todo)=>count + !todo.completed, 0)
            return this.todos.filter(todo=>!todo.completed).length;
          },
          finishedCount() {
            return this.todos.filter(todo=>todo.completed).length;
          }
        }
    }
</script>
<style scoped="">
 .success {
   background: green;
 }
</style>

// with-react/src/components/TodoFooter.js
import React from 'react';
import * as filterTypes from './filter-types'

export default class TodoFooter extends React.Component {
  render() {
    let {activeTodoCount, filterType, changeFilterType, clearCompleted, completedTodoCount} = this.props;
    let btns = [
      {type: filterTypes.ALL, text: "完成"},
      {type: filterTypes.ACTIVE, text: "未完成"},
      {type: filterTypes.COMPLETED, text: "已完成"}
    ];
    return (
    <div className="row text-center">
      {
        activeTodoCount ? (
        <div className="col-xs-4 ">
          <button className="btn btn-primary" disabled={true}>待办事项数量<a href="#" className="badge">{activeTodoCount}</a>
          </button>
        </div>
        ) : null
      }
      <div className="col-xs-5">
        {
          btns.map(btn => (
          <button className={`btn ${filterType !== btn.type ? 'btn-default' : 'btn-success'} btn-sm`}
                  style={{marginLeft: 10}} onClick={() => changeFilterType(btn.type)}>{btn.text}</button>
          ))
        }
      </div>
      {
        completedTodoCount ? (<div className="col-xs-3">
          <button className="btn btn-danger btn-sm" onClick={() => clearCompleted()}>删除已完成</button>
        </div>) : null
      }
    </div>
    )
  }
}


{/*
<button className={`btn ${filterType!==filterTypes.ALL?'btn-default':'btn-success'} btn-sm`} onClick={()=>changeFilterType(filterTypes.ALL)}>全部</button>
<button className={`btn ${filterType!==filterTypes.ACTIVE?'btn-default':'btn-success'} btn-sm`} style={{marginLeft: 10}} onClick={()=>changeFilterType(filterTypes.ACTIVE)}>未完成</button>
<button className={`btn ${filterType!==filterTypes.COMPLETED?'btn-default':'btn-success'} btn-sm`} style={{marginLeft: 10}} onClick={()=>changeFilterType(filterTypes.COMPLETED)}>已完成</button>*/
}
